[debug] [2023-11-15T03:40:58.008Z] ----------------------------------------------------------------------
[debug] [2023-11-15T03:40:58.012Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\rajee\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-11-15T03:40:58.013Z] CLI Version:   12.8.1
[debug] [2023-11-15T03:40:58.014Z] Platform:      win32
[debug] [2023-11-15T03:40:58.014Z] Node Version:  v18.18.0
[debug] [2023-11-15T03:40:58.017Z] Time:          Wed Nov 15 2023 09:10:58 GMT+0530 (India Standard Time)
[debug] [2023-11-15T03:40:58.017Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-11-15T03:40:58.024Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-11-15T03:40:58.350Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-11-15T03:40:58.351Z] > authorizing via signed-in user (rk488296@gmail.com)
[debug] [2023-11-15T03:40:58.351Z] [iam] checking project social-sync-aadc4 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-11-15T03:40:58.353Z] > refreshing access token with scopes: []
[debug] [2023-11-15T03:40:58.355Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-15T03:40:58.355Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-15T03:40:58.867Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2023-11-15T03:40:58.868Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-15T03:40:58.883Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions [none]
[debug] [2023-11-15T03:40:58.883Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions x-goog-quota-user=projects/social-sync-aadc4
[debug] [2023-11-15T03:40:58.883Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-11-15T03:40:59.199Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-11-15T03:40:59.199Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2023-11-15T03:41:01.232Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions 200
[debug] [2023-11-15T03:41:01.232Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions {}
[debug] [2023-11-15T03:41:01.233Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project social-sync-aadc4:

  firebase.projects.get
  firebasehosting.sites.update
[debug] [2023-11-15T03:41:01.234Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/social-sync-aadc4 [none]
[debug] [2023-11-15T03:41:02.195Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/social-sync-aadc4 403
[debug] [2023-11-15T03:41:02.195Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/social-sync-aadc4 {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-11-15T03:41:02.197Z] HTTP Error: 403, The caller does not have permission
[debug] [2023-11-15T03:41:02.614Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (C:\Users\rajee\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:49:12)
    at RetryOperation._fn (C:\Users\rajee\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:285:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to get Firebase project social-sync-aadc4. Please make sure the project exists and your account has permission to access it.
[debug] [2023-11-15T03:41:43.047Z] ----------------------------------------------------------------------
[debug] [2023-11-15T03:41:43.049Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\rajee\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-11-15T03:41:43.050Z] CLI Version:   12.8.1
[debug] [2023-11-15T03:41:43.051Z] Platform:      win32
[debug] [2023-11-15T03:41:43.051Z] Node Version:  v18.18.0
[debug] [2023-11-15T03:41:43.053Z] Time:          Wed Nov 15 2023 09:11:43 GMT+0530 (India Standard Time)
[debug] [2023-11-15T03:41:43.053Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-11-15T03:41:43.162Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-11-15T03:41:43.163Z] > authorizing via signed-in user (rk488296@gmail.com)
[debug] [2023-11-15T03:41:43.163Z] [iam] checking project social-sync-aadc4 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-11-15T03:41:43.166Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions [none]
[debug] [2023-11-15T03:41:43.166Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions x-goog-quota-user=projects/social-sync-aadc4
[debug] [2023-11-15T03:41:43.167Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-11-15T03:41:45.094Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions 200
[debug] [2023-11-15T03:41:45.095Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/social-sync-aadc4:testIamPermissions {}
[debug] [2023-11-15T03:41:45.095Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project social-sync-aadc4:

  firebase.projects.get
  firebasehosting.sites.update
[debug] [2023-11-15T03:41:45.097Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/social-sync-aadc4 [none]
[debug] [2023-11-15T03:41:46.036Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/social-sync-aadc4 403
[debug] [2023-11-15T03:41:46.037Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/social-sync-aadc4 {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-11-15T03:41:46.039Z] HTTP Error: 403, The caller does not have permission
[debug] [2023-11-15T03:41:46.507Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (C:\Users\rajee\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:49:12)
    at RetryOperation._fn (C:\Users\rajee\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:285:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to get Firebase project social-sync-aadc4. Please make sure the project exists and your account has permission to access it.
